Add createConductorHandlers function
restify/conductor pull request #121
Opened 2018-08-30 01:19 UTC by mridgway

Expose a `createConductorHandlers` method to build a middleware chain without registering it directly to the server. This makes conductors usable as just a middleware chain rather than only as a route on a Restify server.

You could imagine this being used in this way:

```
import { createConductorHandlers } from 'restify-conductor'

server.get('/myPath', createConductorHandlers(myConductor))
```

2018-08-31 21:39 UTC, misterdjules commented
Requested reviews from @DonutEspresso and @yunong to get their initial feedback on this.

2018-08-31 22:19 UTC, misterdjules commented
@mridgway Please correct me if I'm wrong, is it correct that the reason for providing this API is so that:

1. Existing Shakti conductors can be used by what would be Shakti on NQ
2. Conductors don't have to be first-class citizens in NQ, since in general it seems Shakti and the Website team would like to move away from conductors

?

2018-09-04 17:16 UTC, mridgway commented
@misterdjules That is correct.

2018-09-04 20:35 UTC, DonutEspresso requested changes
Thanks @mridgway! While this exposes some of the glue that was meant to be internal only, in the end this module must still conform to array of functions required by restify, so this seems like a reasonable level of exposure. 

Can we clone some of tests and convert them to install conductors using this method? We can definitely work with you on this!

2018-09-04 20:35 UTC, DonutEspresso commented on lib/index.js
> +    return [
Can we add an assertion here, like on https://github.com/restify/conductor/pull/121/files#diff-6d186b954a58d5bb740f73d84fe39073R47?

2018-09-04 22:10 UTC, mridgway commented
Makes sense @DonutEspresso. I opened https://github.com/restify/conductor/pull/122 to fix the existing tests and will look at adding new ones for the new API. Under the hood, the existing API is using the new API so I think copying the [unit tests for route installation](https://github.com/restify/conductor/blob/master/test/ConductorSpec.js#L15) should be sufficient.

2018-09-05 19:32 UTC, mridgway commented
@DonutEspresso I added the assertion and unit tests for the `createConductorHandlers` API.

2018-09-06 03:51 UTC, DonutEspresso approved these changes

2018-09-06 03:51 UTC, DonutEspresso commented
Thanks @mridgway 🎉

2018-09-06 03:52 UTC, merged